version: 0.2

os: linux

files:
  - source: /target/deploy/awslearn-codepipeline-build-${CODEBUILD_BUILD_NUMBER}.jar  # Use build number for artifact
    destination: /opt/awslearn-codepipeline  # Adjust the destination to your app directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh  # Pre-install tasks, like stopping services
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh  # Post-install tasks like setting permissions
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh  # Start your Spring Boot app
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh  # Validate that the app is running
      timeout: 300
      runas: root
