version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y  # Ensure the system is up-to-date
      - yum install -y java-21-amazon-corretto-devel  # Install Java 21
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "Java version:"
      - java -version  # Verify Java version
      - echo "Installing Maven 3.x..."
      - yum install -y maven  # Install Maven 3.x
      - echo "Maven version:"
      - mvn -version  # Verify Maven installation

  pre_build:
    commands:
      - echo "Running pre-build commands..."
      - mvn clean || { echo 'mvn clean failed'; exit 1; }  # Clean the project

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn package -DskipTests || { echo 'mvn package failed'; exit 1; }  # Build the project

  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - mkdir -p target/deploy
      - cp target/*.jar target/deploy/

artifacts:
  files:
    - target/deploy/**  # Include the compiled jar in the artifacts
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies
