version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=583959061299.dkr.ecr.ap-south-1.amazonaws.com/awslearnecr
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Running Maven build...
      - mvn clean install   # Ensure the JAR is built
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"awslearn-codepipeline","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/awslearn-codepipeline.jar  # Ensure this path matches the actual JAR file location

env:
  variables:
    DOCKERHUB_USERNAME: mnojpatidar111
    DOCKERHUB_PASSWORD: Mylove143#
