version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Java 17 (Amazon Corretto)
    commands:
      - echo "Installing dependencies or any other setup steps"
  build:
    commands:
      - ./mvnw clean install  # Replace with your actual Maven or Gradle build command
  post_build:
    commands:
      - echo "Any post-build steps or artifact handling"

artifacts:
  files:
    - target/my-spring-boot-app.jar  # Adjust the path to your built JAR file
