version: 0.2

env:
  variables:
    S3_BUCKET_NAME: $S3_BUCKET_NAME  # Fetched from GitHub Secrets or environment variable
    CODEBUILD_NAME: $CODEBUILD_NAME  # Fetched from GitHub Secrets or environment variable
    AWS_REGION: $AWS_REGION  # Fetched from GitHub Secrets or environment variable
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Fetched from GitHub Secrets
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY  # Fetched from GitHub Secrets
    ECR_REPOSITORY: $ECR_REPOSITORY  # Full URI of ECR repository

phases:
  install:
    runtime-versions:
      java: corretto17  # Java 17 using Amazon Corretto
    commands:
      - echo "Setting up environment and installing dependencies"
      - mvn install -DskipTests  # Install dependencies
      - echo "Logging in to Amazon ECR"
      - echo "ECR Repository: $ECR_REPOSITORY"  # Debugging line to check the ECR repository URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ECR_REPOSITORY:latest .
      - echo "Tagging Docker image"
      - docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR"
      - docker push $ECR_REPOSITORY:latest
      - echo "Build completed. Preparing artifacts for deployment."
      - mkdir -p target/deploy
      - cp target/*.jar target/deploy/
      - echo "Artifacts ready in target/deploy"

artifacts:
  files:
    - target/deploy/**
  base-directory: target/deploy
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies
