version: 0.2

phases:
  install:
    commands:
      - echo "Updating the system manoj1..."
      - yum update -y  # Update system packages

      - echo "Ensuring Java 17 is installed..."
      - yum install -y java-17-amazon-corretto-devel  # Java 17 should be installed
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "Java version:"
      - java -version  # Verify Java version

      - echo "Checking for pre-installed Maven..."
      - if ! command -v mvn &> /dev/null; then echo 'Maven not found, attempting to install...'; yum install -y maven; fi
      - export M2_HOME=/usr/share/maven
      - export PATH=$M2_HOME/bin:$PATH
      - echo "Maven version:"
      - mvn -version || { echo 'mvn installation failed'; exit 1; }  # Validate Maven installation

  pre_build:
    commands:
      - echo "Setting JAVA_HOME and PATH for pre-build phase..."
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "Running pre-build commands..."
      - mvn clean || { echo 'mvn clean failed'; exit 1; }  # Clean the project

  build:
    commands:
      - echo "Setting JAVA_HOME and PATH for build phase..."
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "Building the project with Maven..."
      - mvn package -DskipTests || { echo 'mvn package failed'; exit 1; }  # Build the project

  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - mkdir -p target/deploy
      - cp target/*.jar target/deploy/

artifacts:
  files:
    - target/deploy/**  # Include the compiled jar in the artifacts
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies
