version: 0.2

phases:
  install:
    commands:
      - echo "Ensuring correct Java version..."
      - java -version  # Verify Java installation
      - echo "Ensuring correct Maven version..."
      - mvn -version  # Verify Maven installation

  pre_build:
    commands:
      - echo "Running pre-build commands..."
      - mvn clean || { echo 'mvn clean failed'; exit 1; }

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn package -DskipTests || { echo 'mvn package failed'; exit 1; }

  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - mkdir -p target/deploy
      - cp target/*.jar target/deploy/

artifacts:
  files:
    - target/deploy/**
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies
