# Use an official Amazon Corretto 17 image as the base image for Java 17
FROM amazoncorretto:17

# Set the working directory inside the container
WORKDIR /opt/awslearn-codepipeline

# Copy the JAR file generated by the build process to the container's working directory
# This assumes the JAR follows the naming convention set in your build pipeline (buildspec.yml)
COPY target/awslearn-codepipeline-build-*.jar /opt/awslearn-codepipeline/awslearn-codepipeline.jar

# Expose the port on which the application will run (Spring Boot default is 8080)
EXPOSE 8080

# Environment variables can be set here if required for your app
# Example:
# ENV SPRING_PROFILES_ACTIVE=prod

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/opt/awslearn-codepipeline/awslearn-codepipeline.jar"]
